---
- name: Verifying checksum
  hosts: all
  vars_files:
          - files_list.yml
  tasks:
          - name: registering file stats
            stat:
                path: "{{ item.name }}"
            register: test
            with_items: "{{ files }}"

          - name: check if checksum matched
            debug: 
                msg: "checksum matched"
            when: '"{{ item.item.checksum }}" == "{{ item.stat.checksum }}"'
            loop: "{{ test.results }}"

          - name: check if checksum not matched
            debug:
                msg: "checksum not matched"
            when: '"{{ item.item.checksum }}"!= "{{ item.stat.checksum }}"'
            loop: "{{ test.results }}"



